### ISSUE TITLE
Beyond PSCC paper: Change chance constraint level input from λ to ε

### ISSUE THREAD

**Issue by timmyfaraday** [Electa-Git/StochasticPowerModels.jl#32] opened 2021-11-06 13:24 UTC
It seems more appropriate to pass the chance constraint level ε, i.e., the 'percentage' for which a given chance constraint  may be violated, rather than λ, which is the translation of ε in a Gaussian context.

**Comment by kaanyurtseven** [comment] 2023-11-09 12:04
The issue is fixed within pull request #36.

**Closed** 2023-11-09 12:05 UTC
Labels: enhancement
